#!/bin/sh -ex

DB_PASS=$(mcookie)
REMOTE_USER=remote

CHERRYEPG_USER=cherryepg
CHERRYEPG_HOME=/var/lib/cherryepg
CHERRYEPG_DB_USER=cherryepg
CHERRYEPG_DB_NAME=cherry_db
CHERRYEPG_DB_PASS=visnja
CHERRYEPG_WEB_GRP=cherryweb

# configure mysql to listen on all interfacesq
sed -i "s|^bind-address|#bind-address|" /etc/mysql/mariadb.conf.d/50-server.cnf

# generate SSL certs for MySQL remote connections (rerun on firstboot)
/usr/lib/inithooks/firstboot.d/20regen-mysql-certs

# allow remote connections & enable SSL by default
service mysql start
mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '$REMOTE_USER'@'%' IDENTIFIED BY '$DB_PASS';"
turnkey-mysql-ssl enable

# create cherryEPG database and user
mysql -u root -e "CREATE USER '$CHERRYEPG_DB_USER'@localhost IDENTIFIED BY '$CHERRYEPG_DB_PASS';"
mysql -u root -e "CREATE DATABASE $CHERRYEPG_DB_NAME DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
mysql -u root -e "GRANT ALL PRIVILEGES ON $CHERRYEPG_DB_NAME.* TO '$CHERRYEPG_DB_USER@localhost';"
mysql -u root -e "FLUSH PRIVILEGES;"

service mysql stop

# enable tklcp site
sed -Ei "s|^(server.document-root.*=).*|\1 \"/var/www\"|" /etc/lighttpd/lighttpd.conf
lighty-enable-mod tklcp || true

# make the cherryEPG environment
# the user
adduser --system --home $CHERRYEPG_HOME --no-create-home --group --shell /bin/bash $CHERRYEPG_USER
adduser $CHERRYEPG_USER shadow

# directories
cd $CHERRYEPG_HOME
mkdir carousel
mkdir ingest
mkdir log
mkdir scheme
mkdir stock

chown $CHERRYEPG_USER:$CHERRYEPG_USER -R $CHERRYEPG_HOME
find $CHERRYEPG_HOME -type d -exec chmod 770 {} \;

# add cherryweb group used to allow access to web interface
addgroup $CHERRYEPG_WEB_GRP
adduser $CHERRYEPG_USER $CHERRYEPG_WEB_GRP

# make the local CPAN files accesible by $CHERRYEPG_USER
find /usr/local/src/authors -type d -exec chmod o=rx {} \;
find /usr/local/src/authors -type f -exec chmod o=r {} \;

# install CPAN packages as $CHERRYEPG_USER
runuser -l $CHERRYEPG_USER -c 'cpanm -M file:///usr/local/src --installdeps --notest --quiet .'

# get cherryTools
cd $CHERRYEPG_HOME
git clone -b draft --single-branch https://github.com/bojanra/cherryTool
chown $CHERRYEPG_USER:$CHERRYEPG_USER -R $CHERRYEPG_HOME

# get ringelspiel


# initial config
cp cherryTool/config.yml .

# enable ssl for $CHERRYEPG_WEB_GRP
ln -s /lib/systemd/system/stunnel4@.service /etc/systemd/system/multi-user.target.wants/stunnel4@cherryweb.service

# install service
systemctl daemon-reload

systemctl enable ringelspiel
systemctl enable cherryWeb
